/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const AskGeminiResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const ResourceId = IDL.Nat;
export const Flashcard = IDL.Record({
  'id' : ResourceId,
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const FlashcardDeckInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'cards' : IDL.Vec(Flashcard),
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const FlashcardDeck = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'owner' : UserId,
  'cards' : IDL.Vec(Flashcard),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const QuizQuestion = IDL.Record({
  'id' : ResourceId,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const StudySetInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'quizQuestions' : IDL.Vec(QuizQuestion),
  'aiSummary' : IDL.Text,
});
export const StudySet = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'quizQuestions' : IDL.Vec(QuizQuestion),
  'aiSummary' : IDL.Text,
});
export const StudySession = IDL.Record({
  'id' : ResourceId,
  'startedAt' : Timestamp,
  'subject' : IDL.Text,
  'owner' : UserId,
  'aiAssisted' : IDL.Bool,
  'durationSeconds' : IDL.Nat,
});
export const AnalyticsSummary = IDL.Record({
  'soloSeconds' : IDL.Nat,
  'totalDurationSeconds' : IDL.Nat,
  'sessions' : IDL.Vec(StudySession),
  'aiAssistedSeconds' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'onboardingComplete' : IDL.Bool,
  'updatedAt' : Timestamp,
  'studyGoals' : IDL.Vec(IDL.Text),
});
export const StudySessionInput = IDL.Record({
  'startedAt' : Timestamp,
  'subject' : IDL.Text,
  'aiAssisted' : IDL.Bool,
  'durationSeconds' : IDL.Nat,
});
export const AuthError = IDL.Variant({
  'EmailAlreadyExists' : IDL.Null,
  'InvalidCredentials' : IDL.Null,
  'NotAuthenticated' : IDL.Null,
  'InternalError' : IDL.Text,
});
export const LoginResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError });
export const RegisterResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : AuthError,
});
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'studyGoals' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'askGemini' : IDL.Func(
      [IDL.Vec(ChatMessage), IDL.Text],
      [AskGeminiResult],
      [],
    ),
  'createDeck' : IDL.Func([FlashcardDeckInput], [FlashcardDeck], []),
  'createStudySet' : IDL.Func([StudySetInput], [StudySet], []),
  'deleteDeck' : IDL.Func([ResourceId], [IDL.Bool], []),
  'deleteStudySet' : IDL.Func([ResourceId], [IDL.Bool], []),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getDeck' : IDL.Func([ResourceId], [IDL.Opt(FlashcardDeck)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getStudySet' : IDL.Func([ResourceId], [IDL.Opt(StudySet)], ['query']),
  'listDecks' : IDL.Func([], [IDL.Vec(FlashcardDeck)], ['query']),
  'listSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'listStudySets' : IDL.Func([], [IDL.Vec(StudySet)], ['query']),
  'logSession' : IDL.Func([StudySessionInput], [StudySession], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
  'updateDeck' : IDL.Func(
      [ResourceId, FlashcardDeckInput],
      [IDL.Opt(FlashcardDeck)],
      [],
    ),
  'updateStudySet' : IDL.Func(
      [ResourceId, StudySetInput],
      [IDL.Opt(StudySet)],
      [],
    ),
  'upsertProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const AskGeminiResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ResourceId = IDL.Nat;
  const Flashcard = IDL.Record({
    'id' : ResourceId,
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const FlashcardDeckInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'cards' : IDL.Vec(Flashcard),
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const FlashcardDeck = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'owner' : UserId,
    'cards' : IDL.Vec(Flashcard),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const QuizQuestion = IDL.Record({
    'id' : ResourceId,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const StudySetInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'quizQuestions' : IDL.Vec(QuizQuestion),
    'aiSummary' : IDL.Text,
  });
  const StudySet = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'quizQuestions' : IDL.Vec(QuizQuestion),
    'aiSummary' : IDL.Text,
  });
  const StudySession = IDL.Record({
    'id' : ResourceId,
    'startedAt' : Timestamp,
    'subject' : IDL.Text,
    'owner' : UserId,
    'aiAssisted' : IDL.Bool,
    'durationSeconds' : IDL.Nat,
  });
  const AnalyticsSummary = IDL.Record({
    'soloSeconds' : IDL.Nat,
    'totalDurationSeconds' : IDL.Nat,
    'sessions' : IDL.Vec(StudySession),
    'aiAssistedSeconds' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'onboardingComplete' : IDL.Bool,
    'updatedAt' : Timestamp,
    'studyGoals' : IDL.Vec(IDL.Text),
  });
  const StudySessionInput = IDL.Record({
    'startedAt' : Timestamp,
    'subject' : IDL.Text,
    'aiAssisted' : IDL.Bool,
    'durationSeconds' : IDL.Nat,
  });
  const AuthError = IDL.Variant({
    'EmailAlreadyExists' : IDL.Null,
    'InvalidCredentials' : IDL.Null,
    'NotAuthenticated' : IDL.Null,
    'InternalError' : IDL.Text,
  });
  const LoginResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError });
  const RegisterResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError });
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'studyGoals' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'askGemini' : IDL.Func(
        [IDL.Vec(ChatMessage), IDL.Text],
        [AskGeminiResult],
        [],
      ),
    'createDeck' : IDL.Func([FlashcardDeckInput], [FlashcardDeck], []),
    'createStudySet' : IDL.Func([StudySetInput], [StudySet], []),
    'deleteDeck' : IDL.Func([ResourceId], [IDL.Bool], []),
    'deleteStudySet' : IDL.Func([ResourceId], [IDL.Bool], []),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getDeck' : IDL.Func([ResourceId], [IDL.Opt(FlashcardDeck)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getStudySet' : IDL.Func([ResourceId], [IDL.Opt(StudySet)], ['query']),
    'listDecks' : IDL.Func([], [IDL.Vec(FlashcardDeck)], ['query']),
    'listSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'listStudySets' : IDL.Func([], [IDL.Vec(StudySet)], ['query']),
    'logSession' : IDL.Func([StudySessionInput], [StudySession], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
    'updateDeck' : IDL.Func(
        [ResourceId, FlashcardDeckInput],
        [IDL.Opt(FlashcardDeck)],
        [],
      ),
    'updateStudySet' : IDL.Func(
        [ResourceId, StudySetInput],
        [IDL.Opt(StudySet)],
        [],
      ),
    'upsertProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };