/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'soloSeconds' : bigint,
  'totalDurationSeconds' : bigint,
  'sessions' : Array<StudySession>,
  'aiAssistedSeconds' : bigint,
  'totalSessions' : bigint,
}
export interface Flashcard {
  'id' : ResourceId,
  'question' : string,
  'answer' : string,
}
export interface FlashcardDeck {
  'id' : ResourceId,
  'title' : string,
  'subject' : string,
  'owner' : UserId,
  'cards' : Array<Flashcard>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface FlashcardDeckInput {
  'title' : string,
  'subject' : string,
  'cards' : Array<Flashcard>,
}
export interface QuizQuestion {
  'id' : ResourceId,
  'question' : string,
  'correctIndex' : bigint,
  'options' : Array<string>,
}
export type ResourceId = bigint;
export interface StudySession {
  'id' : ResourceId,
  'startedAt' : Timestamp,
  'subject' : string,
  'owner' : UserId,
  'aiAssisted' : boolean,
  'durationSeconds' : bigint,
}
export interface StudySessionInput {
  'startedAt' : Timestamp,
  'subject' : string,
  'aiAssisted' : boolean,
  'durationSeconds' : bigint,
}
export interface StudySet {
  'id' : ResourceId,
  'title' : string,
  'subject' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'quizQuestions' : Array<QuizQuestion>,
  'aiSummary' : string,
}
export interface StudySetInput {
  'title' : string,
  'subject' : string,
  'quizQuestions' : Array<QuizQuestion>,
  'aiSummary' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'onboardingComplete' : boolean,
  'updatedAt' : Timestamp,
  'studyGoals' : Array<string>,
}
export interface UserProfileInput {
  'name' : string,
  'onboardingComplete' : boolean,
  'studyGoals' : Array<string>,
}
export interface _SERVICE {
  'createDeck' : ActorMethod<[FlashcardDeckInput], FlashcardDeck>,
  'createStudySet' : ActorMethod<[StudySetInput], StudySet>,
  'deleteDeck' : ActorMethod<[ResourceId], boolean>,
  'deleteStudySet' : ActorMethod<[ResourceId], boolean>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getDeck' : ActorMethod<[ResourceId], [] | [FlashcardDeck]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStudySet' : ActorMethod<[ResourceId], [] | [StudySet]>,
  'listDecks' : ActorMethod<[], Array<FlashcardDeck>>,
  'listSessions' : ActorMethod<[], Array<StudySession>>,
  'listStudySets' : ActorMethod<[], Array<StudySet>>,
  'logSession' : ActorMethod<[StudySessionInput], StudySession>,
  'updateDeck' : ActorMethod<
    [ResourceId, FlashcardDeckInput],
    [] | [FlashcardDeck]
  >,
  'updateStudySet' : ActorMethod<[ResourceId, StudySetInput], [] | [StudySet]>,
  'upsertProfile' : ActorMethod<[UserProfileInput], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];