/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface AnalyticsSummary {
    soloSeconds: bigint;
    totalDurationSeconds: bigint;
    sessions: Array<StudySession>;
    aiAssistedSeconds: bigint;
    totalSessions: bigint;
}
export interface QuizQuestion {
    id: ResourceId;
    question: string;
    correctIndex: bigint;
    options: Array<string>;
}
export interface FlashcardDeck {
    id: ResourceId;
    title: string;
    subject: string;
    owner: UserId;
    cards: Array<Flashcard>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export type AuthError = {
    __kind__: "EmailAlreadyExists";
    EmailAlreadyExists: null;
} | {
    __kind__: "InvalidCredentials";
    InvalidCredentials: null;
} | {
    __kind__: "NotAuthenticated";
    NotAuthenticated: null;
} | {
    __kind__: "InternalError";
    InternalError: string;
};
export type AskGeminiResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = Principal;
export type RegisterResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AuthError;
};
export interface FlashcardDeckInput {
    title: string;
    subject: string;
    cards: Array<Flashcard>;
}
export interface StudySet {
    id: ResourceId;
    title: string;
    subject: string;
    owner: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    quizQuestions: Array<QuizQuestion>;
    aiSummary: string;
}
export interface StudySetInput {
    title: string;
    subject: string;
    quizQuestions: Array<QuizQuestion>;
    aiSummary: string;
}
export interface Flashcard {
    id: ResourceId;
    question: string;
    answer: string;
}
export interface ChatMessage {
    content: string;
    role: string;
}
export interface StudySession {
    id: ResourceId;
    startedAt: Timestamp;
    subject: string;
    owner: UserId;
    aiAssisted: boolean;
    durationSeconds: bigint;
}
export type LoginResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AuthError;
};
export type ResourceId = bigint;
export interface UserProfileInput {
    name: string;
    onboardingComplete: boolean;
    studyGoals: Array<string>;
}
export interface StudySessionInput {
    startedAt: Timestamp;
    subject: string;
    aiAssisted: boolean;
    durationSeconds: bigint;
}
export interface UserProfile {
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    onboardingComplete: boolean;
    updatedAt: Timestamp;
    studyGoals: Array<string>;
}
export interface backendInterface {
    askGemini(history: Array<ChatMessage>, message: string): Promise<AskGeminiResult>;
    createDeck(input: FlashcardDeckInput): Promise<FlashcardDeck>;
    createStudySet(input: StudySetInput): Promise<StudySet>;
    deleteDeck(id: ResourceId): Promise<boolean>;
    deleteStudySet(id: ResourceId): Promise<boolean>;
    getAnalyticsSummary(): Promise<AnalyticsSummary>;
    getDeck(id: ResourceId): Promise<FlashcardDeck | null>;
    getProfile(): Promise<UserProfile | null>;
    getStudySet(id: ResourceId): Promise<StudySet | null>;
    listDecks(): Promise<Array<FlashcardDeck>>;
    listSessions(): Promise<Array<StudySession>>;
    listStudySets(): Promise<Array<StudySet>>;
    logSession(input: StudySessionInput): Promise<StudySession>;
    login(email: string, password: string): Promise<LoginResult>;
    logout(): Promise<void>;
    register(email: string, password: string): Promise<RegisterResult>;
    updateDeck(id: ResourceId, input: FlashcardDeckInput): Promise<FlashcardDeck | null>;
    updateStudySet(id: ResourceId, input: StudySetInput): Promise<StudySet | null>;
    upsertProfile(input: UserProfileInput): Promise<UserProfile>;
}
import type { AskGeminiResult as _AskGeminiResult, AuthError as _AuthError, FlashcardDeck as _FlashcardDeck, LoginResult as _LoginResult, RegisterResult as _RegisterResult, StudySet as _StudySet, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async askGemini(arg0: Array<ChatMessage>, arg1: string): Promise<AskGeminiResult> {
        if (this.processError) {
            try {
                const result = await this.actor.askGemini(arg0, arg1);
                return from_candid_AskGeminiResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askGemini(arg0, arg1);
            return from_candid_AskGeminiResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDeck(arg0: FlashcardDeckInput): Promise<FlashcardDeck> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeck(arg0);
            return result;
        }
    }
    async createStudySet(arg0: StudySetInput): Promise<StudySet> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudySet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudySet(arg0);
            return result;
        }
    }
    async deleteDeck(arg0: ResourceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeck(arg0);
            return result;
        }
    }
    async deleteStudySet(arg0: ResourceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudySet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudySet(arg0);
            return result;
        }
    }
    async getAnalyticsSummary(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getDeck(arg0: ResourceId): Promise<FlashcardDeck | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeck(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeck(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudySet(arg0: ResourceId): Promise<StudySet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudySet(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudySet(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDecks(): Promise<Array<FlashcardDeck>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDecks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDecks();
            return result;
        }
    }
    async listSessions(): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions();
            return result;
        }
    }
    async listStudySets(): Promise<Array<StudySet>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudySets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudySets();
            return result;
        }
    }
    async logSession(arg0: StudySessionInput): Promise<StudySession> {
        if (this.processError) {
            try {
                const result = await this.actor.logSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSession(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_RegisterResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_RegisterResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDeck(arg0: ResourceId, arg1: FlashcardDeckInput): Promise<FlashcardDeck | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeck(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeck(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudySet(arg0: ResourceId, arg1: StudySetInput): Promise<StudySet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudySet(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudySet(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertProfile(arg0: UserProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProfile(arg0);
            return result;
        }
    }
}
function from_candid_AskGeminiResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AskGeminiResult): AskGeminiResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AuthError_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthError): AuthError {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlashcardDeck]): FlashcardDeck | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudySet]): StudySet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EmailAlreadyExists: null;
} | {
    InvalidCredentials: null;
} | {
    NotAuthenticated: null;
} | {
    InternalError: string;
}): {
    __kind__: "EmailAlreadyExists";
    EmailAlreadyExists: null;
} | {
    __kind__: "InvalidCredentials";
    InvalidCredentials: null;
} | {
    __kind__: "NotAuthenticated";
    NotAuthenticated: null;
} | {
    __kind__: "InternalError";
    InternalError: string;
} {
    return "EmailAlreadyExists" in value ? {
        __kind__: "EmailAlreadyExists",
        EmailAlreadyExists: value.EmailAlreadyExists
    } : "InvalidCredentials" in value ? {
        __kind__: "InvalidCredentials",
        InvalidCredentials: value.InvalidCredentials
    } : "NotAuthenticated" in value ? {
        __kind__: "NotAuthenticated",
        NotAuthenticated: value.NotAuthenticated
    } : "InternalError" in value ? {
        __kind__: "InternalError",
        InternalError: value.InternalError
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
